feat(watchuserposition.ts): временно добавил alert для ошибки геолокации
web-search-for-the-nearest-hospitals/Frontend pull request #31
Opened 2023-12-21 12:33 UTC by rdevil23

2023-12-21 18:02 UTC, Art-Frich requested changes

2023-12-21 18:02 UTC, Art-Frich commented on src/entities/user/lib/watchUserPosition.ts
> +    },
Крч подключай свою библу и красиво прикрути всплывашку. Дизайн в целом не против, но паникует, что у них нет дизайнерской библы. Всё очень просто, нам надо обрабатывать ошибку, пока дизайн ничего умного не придумал, мы практикуемся и делаем в силу своих способностей. По итогу, лучше какая-то реализация, чем запоздалый красивый макет. Ну а если дизайн будет категорически против, то когда-нибудь, быть может, доберутся руки и переделаем. Пока нам нужно быстро и красиво. Сделаешь - покажешь всем как работать с библой.

В целом же, такую реализацию не понял.
=> {
alert(...)
console.error(....)
}

будет достаточно, try-catch это over какой-то

2023-12-22 16:44 UTC, Art-Frich requested changes

2023-12-22 16:44 UTC, Art-Frich commented on package-lock.json
> +    },
это автоматически подтягивается? или вручную нужно?

2023-12-22 16:44 UTC, Art-Frich commented on src/app/index.css
> +
перенеси константы в ~/shared/lib/constants.scss

2023-12-22 16:44 UTC, Art-Frich commented on src/app/index.tsx
> +      />
Вынеси компонент в widgets. Т.е. он станет автономным. Вся логика компонента - его настройки, импорт стилей - будут внутри. И в следующий раз переносишь в новый проект папкой. Внутри можешь создать модификацию пропсов одну или несколько (для storybook и дизайнеров). И выбирать модификацию мы будем там, где этот виджет подключаем. Чтобы не было полотна пропсов. Хотя мб Вера поддержит твоё решение

2023-12-22 16:44 UTC, Art-Frich commented on src/app/index.tsx
> +import 'react-toastify/dist/ReactToastify.css';
а почему импорт идёт в dist? это же build-версия? Как они связаны?

2023-12-22 16:44 UTC, Art-Frich commented on src/entities/user/constants/positionNotifications.ts
entitites - слой
user - срез
constants - сегмент

согласно fsd внутри среза нейминг сегментов жестко регламентирован: см доку к проекту
![image](https://github.com/web-search-for-the-nearest-hospitals/Frontend/assets/119933133/fe678146-0797-478e-ae08-ae8f24b95f27)

т.е. вместо constants нужно выбрать сегмент lib - для utils, contants, hooks.

https://feature-sliced.design/ru/docs/reference/slices-segments - о сегментах.

2023-12-22 16:44 UTC, Art-Frich commented on src/entities/user/constants/positionNotifications.ts
> +const successPositionMessage = 'Отображены результаты для вашей геолокации.';
текст ошибок лучше вынести непосредственно в constants.ts

получится
-lib
--constants.ts
--positionNotifications.ts

2023-12-22 17:13 UTC, rdevil23 commented on package-lock.json
> +    },
автоматически после установки библы командой 
`npm install --save react-toastify`
с доки: https://fkhadra.github.io/react-toastify/installation

2023-12-22 17:16 UTC, rdevil23 commented on src/entities/user/constants/positionNotifications.ts
упустил, исправлю

2023-12-22 17:17 UTC, rdevil23 commented on src/entities/user/constants/positionNotifications.ts
> +const successPositionMessage = 'Отображены результаты для вашей геолокации.';
да, конечно, закрутился с fsd и забыл

2023-12-22 18:10 UTC, rdevil23 commented on src/app/index.tsx
> +      />
В виджет вынес.
По модификации пропсов позже посмотрю.

2023-12-22 18:31 UTC, rdevil23 commented on src/app/index.tsx
> +import 'react-toastify/dist/ReactToastify.css';
Это импорт стандартных стилей по доке: https://fkhadra.github.io/react-toastify/installation#the-gist

2023-12-22 18:54 UTC, Art-Frich commented on src/widgets/notification-container/ui/index.tsx
> +import '../../../shared/lib/Constants.scss';
Не вполне понимаю зачем сюда подключать отдельно константы из shared, т.к. по идее они подключаются в index.scss на App уровне. Расскажите, мб не в курсе чего

В общем
Как вёрсткой будешь заниматься, попробуй это отсюда вынести и подключить константы стилей глобально в App. По идее должно работать. Фикс мелкий, отклонять не буду

2023-12-22 18:54 UTC, Art-Frich commented on src/widgets/notification-container/ui/index.scss
Если он будет и дальше пустым, то его нужно будет удалить

2023-12-22 18:55 UTC, Art-Frich approved these changes

2023-12-22 18:56 UTC, merged

2023-12-22 19:01 UTC, Art-Frich commented on src/app/index.tsx
> +      />
> В виджет вынес. По модификации пропсов позже посмотрю.

не обязательный момент, но мб полезно

2023-12-26 09:33 UTC, rdevil23 commented on src/widgets/notification-container/ui/index.tsx
> +import '../../../shared/lib/Constants.scss';
Подключил глобально

2023-12-26 09:33 UTC, rdevil23 commented on src/widgets/notification-container/ui/index.scss
Удалил