Feat/form
web-search-for-the-nearest-hospitals/Frontend pull request #53
Opened 2024-01-04 23:02 UTC by IIKolchin

2024-01-06 02:08 UTC, Art-Frich requested changes
* В консоли ошибки и спам из данных
![image](https://github.com/web-search-for-the-nearest-hospitals/Frontend/assets/119933133/4928dc16-8f95-4723-94ea-431213708534)
![image](https://github.com/web-search-for-the-nearest-hospitals/Frontend/assets/119933133/fbf237e6-767e-48a9-b393-1d48f6e20b10)
*  сломана карта - больше не переключаются районы
*  нужно обсудить интеграцию моих кастомных инпутов и твоей реализации их в форме
! интеграцию нужно именно обсудить (для начала).

2024-01-06 02:08 UTC, Art-Frich commented on src/pages/index.tsx
> +      <Route path="/clinic-searcher/appointment" element={<AppointmentPage />} />
Чтобы через f5 корректно обновлялась страничка, нужно в vite.config изменить на   base: '/',
хз чего там куда накладывается, но если обнулить base, то робит корректно, а иначе багует при обновлении. 

Вроде и логично багует, а вроде и не очень

2024-01-06 02:08 UTC, Art-Frich commented on src/widgets/form-appointment/ui/index.tsx
Моя основная претензия к RHF - он громоздкий. С одной стороны, с некоторыми оговорками, он упрощает парсинг данных в форму и его отправку, с другой - мы получили компонент на ~180 строк.

Неужели нет способа разбить форму на более мелкие запчасти? RHF настолько хардкожен, что может работать только в рамках одной странички?

2024-01-06 12:39 UTC, IIKolchin commented on src/app/store/store.ts
> +export default store;
смысл, что добавились еще экспорты, а по умолчанию по идее эксортируется только стор. В чем сакральный смысл, тут не отвечу))

2024-01-06 12:44 UTC, IIKolchin commented on src/shared/ui/Input/input.tsx
> +  onBlur: (event: ChangeEvent<HTMLInputElement>) => void;
он будет использоваться, когда в инпут ввел неправильное значение, и начал в другой вводить, то при потере фокуса на предыдущем инпуте сработает onBlur и покажется сразу ошибка, а не при сабмите формы. Не доделал я просто))

2024-01-06 12:46 UTC, IIKolchin commented on src/widgets/form-appointment/ui/index.tsx
> +              }}
ага, все печально, обычно, чтоб не париться как раз и используют mui)

2024-01-06 12:48 UTC, Art-Frich commented on src/app/store/store.ts
> +export default store;
А, точно. Не, не варик. Я же подключил стор без этих экспортов ранее. Почему не посмотрел как? 
Это нарушение принципа FSD. Мы импортируем RootState и AppDispatch из store, который лежит в App. Чтобы обойти эту философскую дилемму, я создал глобальные типы (скрин ниже)
![image](https://github.com/web-search-for-the-nearest-hospitals/Frontend/assets/119933133/0b988fb0-268a-4a61-b1bb-68849ec1cccc)

2024-01-06 12:52 UTC, Art-Frich commented on src/app/store/store.ts
> +export default store;
![image](https://github.com/web-search-for-the-nearest-hospitals/Frontend/assets/119933133/65faf5a8-c125-478d-bd69-ea068ac2ad05)

2024-01-06 12:59 UTC, IIKolchin commented on src/widgets/form-appointment/ui/index.tsx
> +          render={({ field }) => (
field это объект, который содержит разные свойства и методы для интеграции с библиотекой react hook form. Например field.onChange меняет значение поля (как видно дальше из кода), field.name, field.value, и т.д., т.е. с помощью этих свойств и методов библитека получает доступ к инпутам и селектам

2024-01-06 13:00 UTC, IIKolchin commented on src/widgets/form-appointment/ui/index.tsx
какую альтернативу предложишь?

2024-01-06 13:31 UTC, IIKolchin commented on src/shared/ui/Checkbox/Checkbox.tsx
> +    <label className={`${styles['checkbox']} ${className || ''}`}>
да, видел cn, надо будет обновить по всему проекту

2024-01-08 17:08 UTC, Art-Frich commented on src/shared/ui/Checkbox/Checkbox.tsx
> +    <label className={`${styles['checkbox']} ${className || ''}`}>
> да, видел cn, надо будет обновить по всему проекту

Не обязательно везде его пихать. Толк от него заметен, когда много классов, но количество кода от этого не изменится. Просто синтаксис попроще

2024-01-08 17:26 UTC, Art-Frich commented on src/widgets/form-appointment/ui/index.tsx
> какую альтернативу предложишь?

Ну прежде всего спрашиваю: неужели нельзя разбить на подкомпоненты? RHF не работает, если контроллеры прокидывать пропсами? Примеров таких я не виделю

Не использовать RHF.  В большинстве случаев в нём нет необходимости. На этой форме оно имеет смысл, но 180 строчек меня печалят. 

Красиво конечно у них в доке формы на 6-30 строк, но у нас то что-то поболе выходит. Это мне и не нравится.

В целом же возникает такой момент: RHF работает с неконтролируемыми инпутами (одна из его сильных фичей), у нас они кастомные и контролируемые по умолчанию. Нет подкапотного стейта, всё придется вручную менять. И реакт (дока) в принципе рекомендует контролировать инпуты.

Опять же, RHF - самый популярный из менеджеров, а значит у этого есть причины. Но я видел вот 2 реализации RHF в проекте и каждый раз это выглядит грустно. Без RHF появляется возня со стейтами, а с ним  - здоровенные компоненты.

2024-01-20 22:38 UTC, rdevil23 commented on src/shared/ui/DropDownInput/DropDownInput.tsx
> +  ref?: LegacyRef<HTMLInputElement> | undefined | null;
1) Вроде при `?:` можно не указывать `undefined`.

2) Вообще LegacyRef что-то новенькое, а точнее старенькое.
Не очень нравится его присутствие, мы не можем от него отказаться?
Строки 24-26 разве не содержат все необходимое нам решение?

2024-01-20 22:47 UTC, rdevil23 commented on src/shared/ui/DropDownInput/DropDownInput.tsx
> +    <div className={styles['drop-down-input']} ref={ref}>
3) Раз в `<div>` передаем то наверно `HTMLDivElement`?

2024-01-20 23:20 UTC, rdevil23 commented on src/shared/ui/DropDownInput/DropDownInput.tsx
>          onBlur={handleBlur}
line: 60 `data-key={listKey}` тоже первый раз вижу, тоже вроде сомнительно, либо не до конца понимаю для чего.

2024-01-20 23:52 UTC, rdevil23 commented on src/shared/ui/DropDownInput/_useDropDownInput.ts
Сильно насыщенный файл получился, здесь уже подустал смотреть его.
Может декомпозировать? У нас же это хук обработки выпадающего меню? А `onKeyInput` и `onKeyOption` обрабатывают нажатия на кнопки, но ведь это может переиспользоваться?. Так может их вынести в хук, условно: `useKeyHandler` ?

2024-01-21 15:37 UTC, Art-Frich commented on src/shared/ui/DropDownInput/DropDownInput.tsx
> +  ref?: LegacyRef<HTMLInputElement> | undefined | null;
О, друг, я понятия не имею о смысловой нагрузки этой части кода. 

Вот я и на распутье. Тут есть полезный код, но бесполезного навалом. И я заколебался рефакторить, разделяя и чиня конфликты.

2024-01-21 15:37 UTC, Art-Frich commented on src/shared/ui/DropDownInput/DropDownInput.tsx
> +    <div className={styles['drop-down-input']} ref={ref}>
Не вижу к чему коммент, но HTMLDivElement точно будет вернее

2024-01-21 15:40 UTC, Art-Frich commented on src/shared/ui/DropDownInput/DropDownInput.tsx
>          onBlur={handleBlur}
Это же не этого ПР изменение =)
аналог key для списков
нужен, чтобы обработчики кликов различали разные dropDownInput

2024-01-21 15:41 UTC, Art-Frich commented on src/shared/ui/DropDownInput/_useDropDownInput.ts
Попробуй. Получится - будешь большой молодец. Я потратил на это вечер и понял, что легче не стало. Больше тратить сил не вижу смысла

2024-01-21 15:42 UTC, Art-Frich commented on src/shared/ui/DropDownInput/_useDropDownInput.ts
В чём проблема? 
Много перекрёстных стейтов и обработчиков.
Если разнести функционал, то количество прокидываемых на вход пропсов становится очень велико. Код становится перегружен импортами и пропсами, а логика разносится по файлам, но общая картинка легче не становится. 
ИМХО

2024-01-21 17:46 UTC, closed without merging