feat: график работы с бд
web-search-for-the-nearest-hospitals/Frontend pull request #65
Opened 2024-01-13 13:28 UTC by rdevil23

2024-01-13 22:58 UTC, Art-Frich requested changes
![image](https://github.com/web-search-for-the-nearest-hospitals/Frontend/assets/119933133/85542066-f8c6-481f-a9e8-dce905b78c9e)
Решил алгоритмическую задачку по своему замыслу.

```
const weekdaysHours = <T extends IBusinessHours>(data: T[]) => {
    const res = [];
    const days: { [key: number]: string } = {
      1: 'пн',
      2: 'вт',
      3: 'ср',
      4: 'чт',
      5: 'пт',
      6: 'сб',
      7: 'вс',
    };
    const getTime = (time: string) => time.slice(0, -3);

    for (let i = 0; i < 7; i++) {
      // если день есть в данных с бэка
      if (data[i] !== undefined) {
        const { day: st, from_hour, to_hour } = data[i]!;

        // пока рабочие часы совпадают
        while (from_hour === data[i + 1]?.from_hour && to_hour === data[i + 1]?.to_hour) i++;

        //                 i остался прежним ?
        const interval = st === data[i]!.day ? days[st] : `${days[st]}-${days[data[i]!.day]}`;
        res.push(`${interval}: ${getTime(from_hour)}-${getTime(to_hour)}`);
      } else {
        // если дня в данных нет
        res.push(`${days[i + 1]}: Выходной`);
      }
    }

    return res.join('\n ');
  };
```

Здесь важно что... это алгоритмическая задачка. Решение её считается правильным, когда удовлетворяет требованиям бизнеса. Устойчивым, когда всевозможные комбинации входных данных обрабатываются корректно (даже околоневозможные). И оптимальным, когда сложность алгоритма является линейной O(n) или ниже (в некоторых случаях линейная сложность будет чрезмерной).
![image](https://github.com/web-search-for-the-nearest-hospitals/Frontend/assets/119933133/80737ca0-c335-440a-bd14-891e6598d79d)

Таким образом, я просто хотел решить задачку сам и показать альтернативное решение тебе. Это не значит, что твоё решение надо удалить. Но сейчас его точно нужно доработать

P.S. + я своё на баги не тестил. Мб тоже косяки есть

UPD: оптимальность мб рассмотрена также с точки зрения потребляемой памяти, а не только времени работы. Для нашего случая из 7-ми дней - это просто рассуждения о паттернах.

UPD: рассуждая о краевых случаях нашел кейсы, которые не обработал у себя: 
* круглосуточные поликлиники - это лучше выводить словом, а не 00-00.
* несколько выходных подряд
* выходные посреди недели ломают индексацию

![image](https://github.com/web-search-for-the-nearest-hospitals/Frontend/assets/119933133/a2ac5c65-e5fe-4ac6-90ee-6bba5e1023ce)

2024-01-13 22:58 UTC, Art-Frich commented
> ![image](https://private-user-images.githubusercontent.com/119933133/296518974-85542066-f8c6-481f-a9e8-dce905b78c9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxODY5ODksIm5iZiI6MTcwNTE4NjY4OSwicGF0aCI6Ii8xMTk5MzMxMzMvMjk2NTE4OTc0LTg1NTQyMDY2LWY4YzYtNDgxZi1hOWU4LWRjZTkwNWI3OGM5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QyMjU4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTQ3MDBjNWM1YjIxOTNjZTZjM2E5YTRiNTY4NWRlZWQ5ZGRmOTc5ZjJkNzUzZmYxNWE2ODIzOTQ4MWIzMzMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t--DChcng0UnBh8wrYO-M5gdlxMWdyck-RN9kUAboI8) Решил алгоритмическую задачку по своему замыслу.
> 
> ```
> const weekdaysHours = <T extends IBusinessHours>(data: T[]) => {
>     const res = [];
>     const days: { [key: number]: string } = {
>       1: 'пн',
>       2: 'вт',
>       3: 'ср',
>       4: 'чт',
>       5: 'пт',
>       6: 'сб',
>       7: 'вс',
>     };
>     const getTime = (time: string) => time.slice(0, -3);
> 
>     for (let i = 0; i < 7; i++) {
>       // если день есть в данных с бэка
>       if (data[i] !== undefined) {
>         const { day: st, from_hour, to_hour } = data[i]!;
> 
>         // пока рабочие часы совпадают
>         while (from_hour === data[i + 1]?.from_hour && to_hour === data[i + 1]?.to_hour) i++;
> 
>         //                 i остался прежним ?
>         const interval = st === data[i]!.day ? days[st] : `${days[st]}-${days[data[i]!.day]}`;
>         res.push(`${interval}: ${getTime(from_hour)}-${getTime(to_hour)}`);
>       } else {
>         // если дня в данных нет
>         res.push(`${days[i + 1]}: Выходной`);
>       }
>     }
> 
>     return res.join('\n ');
>   };
> ```
> 
> Здесь важно что... это алгоритмическая задачка. Решение её считается правильным, когда удовлетворяет требованиям бизнеса. Устойчивым, когда всевозможные комбинации входных данных обрабатываются корректно (даже околоневозможные). И оптимальным, когда сложность алгоритма является линейной O(n) или ниже (в некоторых случаях линейная сложность будет чрезмерной). ![image](https://private-user-images.githubusercontent.com/119933133/296519058-80737ca0-c335-440a-bd14-891e6598d79d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxODY5ODksIm5iZiI6MTcwNTE4NjY4OSwicGF0aCI6Ii8xMTk5MzMxMzMvMjk2NTE5MDU4LTgwNzM3Y2EwLWMzMzUtNDQwYS1iZDE0LTg5MWU2NTk4ZDc5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QyMjU4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Mzk2NzBjZjc3YTY4ODNiMDZlYzUxNjA0NWVmNTIyZmYxNzdiMDNjYjc5MjYyZWYwNDUxZmEwMGMzM2NhMzJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zY8r21p9eiJh_7dZIWOIxuGpZpabB2uHMDMzVduHxCs)
> 
> Таким образом, я просто хотел решить задачку сам и показать альтернативное решение тебе. Это не значит, что твоё решение надо удалить. Но сейчас его точно нужно доработать
> 
> P.S. + я своё на баги не тестил. Мб тоже косяки есть

UP

2024-01-13 23:38 UTC, Art-Frich commented
![image](https://github.com/web-search-for-the-nearest-hospitals/Frontend/assets/119933133/38c01f1f-b11d-4476-ad4a-d9369e1c9118)
прочитал после того, как прокомментил

2024-01-15 16:56 UTC, rdevil23 commented on src/entities/advert/ui/AdvertList/AdvertList.tsx
> +      <span className="advert-list__margin-bottom"></span>
Сейчас обернул список в контейнер и padding уже на него повесил, это вроде адекватное и работающее решение при работе с переполнением.
Если что: padding переполнение не понимает, а margin на last-child просто уходил за контейнер.

2024-01-18 07:46 UTC, Art-Frich commented on src/entities/clinic/ui/ClinicCard/ClinicCard.tsx
>  export function ClinicCard({ clinic, isOpenCard }: IClinicCard) {
эта строчка должна быть вместо 9-ой

2024-01-18 07:50 UTC, Art-Frich commented on src/entities/clinic/ui/ClinicCard/ClinicCard.tsx
> +  const weekdaysHours = () => {
функция должна начинаться с глагола в большинстве случаев. Что она делает? возвращает расписание, значит: getWorkHours - например. Ну или твоя функция: getWeekdayHours.

Ну и вынеси ты её в lib.
clinic/lib/getWeekdayHours.ts

2024-01-18 16:53 UTC, rdevil23 commented on src/entities/clinic/ui/ClinicCard/ClinicCard.tsx
> +    });
Подправил.
Единственное - не нашел, как в это предупреждение провалиться?

2024-01-18 16:58 UTC, rdevil23 commented on src/entities/clinic/ui/ClinicCard/ClinicCard.tsx
> +      // hours === '00:00-00:00' && (hours = '24 часа в сутки');
Тогда пока что будет "24ч", т.к. "круглосуточно" много места занимает и портит визуал.

2024-01-19 02:14 UTC, Art-Frich commented
Отличная работа!

2024-01-19 02:15 UTC, merged