feat(fullcardclinic): Вместо параграфа добавлена ссылка для вызова
web-search-for-the-nearest-hospitals/Frontend pull request #89
Opened 2024-01-21 02:41 UTC by DariaBold

2024-01-21 14:32 UTC, verabald reviewed
Хорошей практикой будет, если эта функция будет отрабатываться только на разрешениях экрана планшета и ниже. Какой процент людей звонит с компьютера?
+ тогда же добавляется и цвет текста, как у сайта, чтобы было понятно, что это рабочая ссылка.

2024-01-21 16:27 UTC, verabald reviewed
У меня сейчас не отрабатывает.

2024-01-21 16:27 UTC, verabald commented on src/entities/clinic/ui/FullCardClinic/FullCardClinic.tsx
> +  function getDevice() {
Поделись откуда взяла.

2024-01-21 16:47 UTC, DariaBold commented on src/entities/clinic/ui/FullCardClinic/FullCardClinic.tsx
> +  function getDevice() {
https://sky.pro/media/kak-opredelit-tip-ustrojstva-polzovatelya-s-pomoshhyu-javascript/
Можно еще через window.innerwidth

2024-01-21 17:47 UTC, Art-Frich commented on src/entities/clinic/ui/FullCardClinic/FullCardClinic.tsx
> +    }
return isPhone;

2024-01-21 17:50 UTC, Art-Frich commented
> Хорошей практикой будет, если эта функция будет отрабатываться только на разрешениях экрана планшета и ниже. Какой процент людей звонит с компьютера?
> 
> * тогда же добавляется и цвет текста, как у сайта, чтобы было понятно, что это рабочая ссылка.

А можно ссылку на хорошую практику? =)

2024-01-21 17:52 UTC, Art-Frich commented
> Хорошей практикой будет, если эта функция будет отрабатываться только на разрешениях экрана планшета и ниже. Какой процент людей звонит с компьютера?
> 
> * тогда же добавляется и цвет текста, как у сайта, чтобы было понятно, что это рабочая ссылка.

Я бы просто при наведении подсвечивал. Пользователь когда будет пытаться скопировать словит hover, а на телефоне клик уже отработает как надо, но это дизайн

2024-01-21 17:53 UTC, Art-Frich commented on src/entities/clinic/ui/FullCardClinic/FullCardClinic.tsx
> +  function getDevice() {
window.screen.width

2024-01-21 17:54 UTC, verabald commented
> > Хорошей практикой будет, если эта функция будет отрабатываться только на разрешениях экрана планшета и ниже. Какой процент людей звонит с компьютера?
> > 
> > * тогда же добавляется и цвет текста, как у сайта, чтобы было понятно, что это рабочая ссылка.
> 
> А можно ссылку на хорошую практику? =)

ПроДокторов в твоём распоряжении.

2024-01-21 17:56 UTC, Art-Frich commented on src/entities/clinic/ui/FullCardClinic/FullCardClinic.tsx
> +  function getDevice() {
getIsPhone тогда уж
или checkDevice

но мне в принципе не нравится получившаяся конструкция, так что можете сделать вид, что не заметили этого коммента

2024-01-21 18:08 UTC, Art-Frich commented on src/entities/clinic/ui/FullCardClinic/FullCardClinic.tsx
> +        )}
<a href={`tel:${clinic.phone}`} style={{ pointerEvents: getDevice() ? 'none' : 'auto' }}>
  <p className={'clinic-popup__phone-number' + getDevice() ? 'clinic-popup__phone-number_active' : ''}>
    {clinic.phone}
  </p>
</a>

подключить classnames зависимость или переписать на шаблонную строку и станет симпатичнее

2024-01-25 18:22 UTC, Art-Frich commented
> > > Хорошей практикой будет, если эта функция будет отрабатываться только на разрешениях экрана планшета и ниже. Какой процент людей звонит с компьютера?
> > > 
> > > * тогда же добавляется и цвет текста, как у сайта, чтобы было понятно, что это рабочая ссылка.
> > 
> > 
> > А можно ссылку на хорошую практику? =)
> 
> ПроДокторов в твоём распоряжении.

Ну какой-то сайт не может быть хорошей практикой, это просто пример, что кто-то так делает

Кто-то всё ещё на php верстает и jquery заставляет джунов учить, но хорошей практикой оно не стало от этого

2024-01-25 18:29 UTC, Art-Frich requested changes

2024-01-25 18:29 UTC, Art-Frich commented on src/entities/clinic/ui/FullCardClinic/FullCardClinic.tsx
> +//     </div>
а зачем это здесь?

2024-01-25 18:29 UTC, Art-Frich commented on src/entities/clinic/ui/FullCardClinic/FullCardClinic.tsx
>        return false;
Не понимаю

зачем так громоздко то

Или это прям мегаудобно по сравнению с 
```
const getIsPhone  = () => window.screen.width < 625;
```
или
```
  function getIsPhone() {
    const width = window.screen.width;
    retrun width < 625
```

приведите мне пожалуйста обоснование такой конструкции, потому что комментарий я оставил в прошлый раз, а это место не изменилось, но мне никто ничего не ответил

2024-01-25 19:37 UTC, DariaBold commented on src/entities/clinic/ui/FullCardClinic/FullCardClinic.tsx
> +//     </div>
я вроде удалила это место

2024-01-25 19:40 UTC, DariaBold commented on src/entities/clinic/ui/FullCardClinic/FullCardClinic.tsx
>        return false;
мне так легче понять что происходит, изменю

2024-01-25 21:37 UTC, Art-Frich commented on src/entities/clinic/ui/FullCardClinic/FullCardClinic.tsx
>        return false;
> мне так легче понять что происходит, изменю

А вот это уже аргумент. Поддержка читаемости кода важна. Поэтому впредь и далее просто так и отвечай, быть может я просто скажу "лан" и делов то

2024-01-25 21:39 UTC, Art-Frich approved these changes

2024-01-25 22:43 UTC, merged