Feat/user icon
web-search-for-the-nearest-hospitals/Frontend pull request #90
Opened 2024-01-21 10:16 UTC by lomeshyza

Добавила IconBtn в нее как children помещаются иконки, пока это UserIcon в виде svg и BtnCloseIcon в виде img , который стилизуется на месте(сейчас в карточке клиники).

2024-01-21 15:31 UTC, Art-Frich requested changes
Подтяни актуальную версию. Попало много экспериментального кода, который больше не актуален и может сломать deploy. 

Ключевой момент: вынести крестик из fullCardClinic

Можно возражать! Например позвать Веру =)

2024-01-21 15:31 UTC, Art-Frich commented on src/entities/clinic/ui/FullCardClinic/FullCardClinic.tsx
Категорически, вопиюще возражаю.

Дело в том, что в момент, когда мы добавляем крестик в FullCardClinic, мы смешиваем логику Popup с FullCardClinic. Т.е. мы смешали совершенно независимые друг от друга сущности. FullCardClinic может быть использован и без Popup, тогда этот крестик будет только смущать людей.

А что делать?
1. Прокидывать этот крести children в компонент, а логику его вынести куда-то (эт надо ещё подумать - куда)
2. Наиболее корректным мне кажется создать внутри Popup пустую обёртку section или div, задать ей минимальные размеру (необязательно) и относительно этой обёртки абсолютно позиционируя создать крестик. Таким образом у всех Popup элементов будет крестик и он никак не связан с содержимым Popup.

Здесь может возникнуть проблема кастомизации крестика ( у разных popup элементов разный крестик), тогда стоит подумать над модификаторами. Я это к тому, что вопрос на перспективу решается.
3. Можно придумать что-то ещё

2024-01-21 15:31 UTC, Art-Frich commented on src/shared/api/rtkqueryApi.ts
> +console.log((import.meta.env.VITE_BACK_URL || process.env['VITE_BACK_URL']) + 'api/');
подтяни актуальную версию develop, этого не должно быть

2024-01-21 15:31 UTC, Art-Frich commented on src/shared/api/rtkqueryApi.ts
> +    baseUrl: (import.meta.env.VITE_BACK_URL || process.env['VITE_BACK_URL']) + 'api/',
|| process.env['VITE_BACK_URL']) - подтяни актуальную версию develop, этого не должно быть

2024-01-21 15:31 UTC, Art-Frich commented on src/shared/api/api.ts
> +const BACK_URL = import.meta.env.VITE_BACK_URL || process.env['VITE_BACK_URL'];
|| process.env['VITE_BACK_URL']) - подтяни актуальную версию develop, этого не должно быть

2024-01-21 15:31 UTC, Art-Frich commented on src/shared/assets/icons/BtnCloseIcon.tsx
> +    </svg> */
код больше не нужен, правильно? Значит его нужно удалить. Иначе прокомментировать: когда и для чего он нужен

2024-01-21 15:31 UTC, Art-Frich commented on src/shared/assets/icons/UserIcon.tsx
> +export default function UserIcon({ width, height }: IUserIcon) {
значения по умолчанию!
{ width = 20, height = 30} - например

2024-01-21 15:31 UTC, Art-Frich commented on src/shared/ui/IconBtn/IconBtn.tsx
> +  //children: () => JSX.Element;
код больше не нужен, правильно? Значит его нужно удалить. Иначе прокомментировать: когда и для чего он нужен

2024-01-21 15:31 UTC, Art-Frich commented on src/shared/ui/IconBtn/IconBtn.tsx
> +} */
код больше не нужен, правильно? Значит его нужно удалить. Иначе прокомментировать: когда и для чего он нужен

2024-01-21 15:31 UTC, Art-Frich commented on src/shared/ui/Maps/ui/index.tsx
> +          apikey: import.meta.env.VITE_YAMAP_API_KEY || process.env['VITE_YAMAP_API_KEY'],
|| process.env['VITE_YAMAP_API_KEY'] - подтяни актуальную версию develop, этого не должно быть

2024-01-21 15:31 UTC, Art-Frich commented on src/widgets/header/ui/index.tsx
> +        <div className="header__container">
проверь выравние по центру. Визуально кажется иконка профиля прижата к верхнему краю
![image](https://github.com/web-search-for-the-nearest-hospitals/Frontend/assets/119933133/e604bcb9-6706-436f-97ea-68149987d998)

2024-01-21 15:31 UTC, Art-Frich commented on src/widgets/searcher-block/ui/index.tsx
> +            }}
onClick={() => console.log('I work')} - лаконичнее

а если хочешь действительно показать его работу - используй фабрику тостов и выбрасывай сообщение по клику
это просто идея. Текущая реализация вполне достаточна

2024-01-25 10:18 UTC, Art-Frich requested changes
Главное поправь слеш в api, иначе деплой тоже сломается, а не только код других разработчиков. В остальном норм, но идеи для улучшения оставил. Они не являются обязательными в рамках этой задачи.

2024-01-25 10:18 UTC, Art-Frich commented on src/shared/api/rtkqueryApi.ts
> +    baseUrl: import.meta.env.VITE_BACK_URL + '/api/',
а-я-яй
Все, кто твою версию скачают - получат сломанный код, т.к. по шаблону BACK_URL уже оканчивается '/'

2024-01-25 10:18 UTC, Art-Frich commented on src/pages/main/ui/index.tsx
> +        </div>
Вот эту кнопку уносим в Popup

2024-01-25 10:18 UTC, Art-Frich commented on src/shared/ui/Popup/Popup.tsx
> +      <div className={cx('popup__container')}>{children}</div>
```
<div className="popup__content">
   <children>
  <IconBtn onClick={() => setIsOpen(false)}>
    <BtnCloseIcon />
  </IconBtn>
</div>
```

А сюда кнопку принесли. Кнопку делаем absolut элементом и крепим в уголок

2024-01-25 10:18 UTC, Art-Frich commented on src/widgets/header/ui/index.tsx
>            <div className="header__icon-button">
Думаю, хорошей идеей будет оставить комментарий, что на странице две таких кнопки и при изменении в одной, нужно внести в другую, чтобы сторонние разработчики сразу в двух местах поправили. Или можно озаботиться выносом конкретно BtnUserIcon в отдельный компонент в entities/ui

2024-01-25 12:12 UTC, lomeshyza commented on src/pages/main/ui/index.tsx
> +        </div>
Если я это все сюда добавлю, то тогда popup перемешается с IconBtn, или их вместе с иконкой надо через props из main прокидывать?

2024-01-25 20:51 UTC, Art-Frich approved these changes

2024-01-25 20:52 UTC, merged